### ISSUE TITLE
Some paragraph node can have no content

### ISSUE THREAD

**Issue by soichih** [julianlam/adf-to-md#2]
Hello. Thank you for publishing this module.

I tried to use this but I am seeing this error message.

```
/home/shayashi/exp/adf2md/node_modules/adf-to-md/index.js:16
                        return node.content.map(node => _convert(node, warnings)).join('');

TypeError: Cannot read properties of undefined (reading 'map')
    at _convert (/home/shayashi/exp/adf2md/node_modules/adf-to-md/index.js:16:24)
```

It looks like confluence is producing a paragraph node without "content" parameter. Here is my document.

```
{
  type: 'doc',
  content: [
    { type: 'paragraph', content: [Array] },
    { type: 'codeBlock', content: [Array] },
    { type: 'paragraph' },
    { type: 'paragraph', content: [Array] },
    { type: 'panel', attrs: [Object], content: [Array] }
  ],
  version: 1
}
```

I just updated `adf-to-md/index.js` to return new line if content is missing in paragraph and it seems to work around it.

**Comment by julianlam** [comment]
> It looks like confluence is producing a paragraph node without "content" parameter. 

Why am I not surprised? :smirk: 

If you can, please open a PR with that change, I'd be happy to merge as-is.

**Comment by honeylizard** [comment]
Still running into this issue with v1.2.1. When the content has a following element `{ "type": "paragraph" }`, it throws a `Error: Cannot read properties of undefined (reading 'map')`

UPDATE: our GHA needed a fresh build to get this change when we bumped version. Working now.
